<?php

namespace Tecnospeed\Assets;

class SendParams {

    public static function params()
    {
        return array(
            'formato'=>'',
            'padrao'=>'',
            'nomeCidade'=>'',
            'idLote'=>'',
            'IdLote'=>'',
            'numeroLote'=>'',
            'versao'=>'2.01',
            'quantidadeRPS'=>'',
            'transacao'=>'',
            'metodoEnvio'=>'',
            'cpfCnpjRemetente'=>'',
            'razaoSocialRemetente' => '',
            'inscricaoMunicipalRemetente'=>'',
            'codigoCidadeRemetente'=>'',
            'dataInicio'=>'',
            'dataFim'=>'',
            'valorTotalServicos'=>'',
            'idIntegracao'=>'',
            'valorTotalBaseCalculo'=>'',
            'valorTotalDeducoes'=>'',
            'idRps'=>'',
            'situacaoNota'=>'',
            'tipoRps'=>'',
            'serieRps'=>'',
            'numeroRps'=>'',
            'dataEmissao'=>'',
            'competencia'=>'',
            'cpfCnpjPrestador'=>'',
            'inscricaoMunicipalPrestador'=>'',
            'razaoSocialPrestador'=>'',
            'codigoCidadePrestacao'=>'',
            'descricaoCidadePrestacao'=>'',
            'optanteSimplesNacional'=>'',
            'incentivadorCultural'=>'',
            'regimeEspecialTributacao'=>'',
            'naturezaTributacao'=>'',
            'incentivoFiscal'=>'',
            'incentivoFiscal'=>'',
            'cpfCnpjTomador'=>'',
            'razaoSocialTomador'=>'',
            'inscricaoEstadualTomador'=>'',
            'tipoLogradouroTomador'=>'',
            'enderecoTomador'=>'',
            'numeroTomador'=>'',
            'complementoTomador'=>'',
            'tipoBairroTomador'=>'',
            'bairroTomador'=>'',
            'codigoCidadeTomador'=>'',
            'descricaoCidadeTomador'=>'',
            'ufTomador'=>'',
            'cepTomador'=>'',
            'paisTomador'=>'',
            'dddTomador'=>'',
            'telefoneTomador'=>'',
            'emailTomador'=>'',
            'codigoItemListaServico'=>'',
            'codigoTributacaoMunicipio'=>'',
            'codigoCnae'=>'',
            'discriminacaoServico'=>'',
            'tipoTributacao'=>'',
            'exigibilidadeISS'=>'',
            'operacao'=>'',
            'municipioIncidencia'=>'',
            'valorServicos'=>'',
            'aliquotaPIS'=>'',
            'aliquotaCOFINS'=>'',
            'aliquotaINSS'=>'',
            'aliquotaIR'=>'',
            'aliquotaCSLL'=>'',
            'valorPIS'=>'',
            'valorCOFINS'=>'',
            'valorINSS'=>'',
            'valorIR'=>'',
            'valorCSLL'=>'',
            'outrasRetencoes'=>'',
            'descontoIncondicionado'=>'',
            'descontoCondicionado'=>'',
            'valorDeducoes'=>'',
            'baseCalculo'=>'',
            'aliquotaISS'=>'',
            'valorIss'=>'',
            'issRetido'=>'',
            'valorISSRetido'=>'',
            'valorLiquidoNfse'=>'',
            'responsavelRetencao'=>''
        );
    }

} 